name: Tests under Miri

on:
  pull_request:
    types: [ opened, edited ]
    paths: 
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  check-toolchains:
    runs-on: ubuntu-latest
    strategy:
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: miri
    - name: Run cargo miri test
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: miri
        args: test --all --all-features
